using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class ScoreManager : MonoBehaviour
{
    public int rightScore; 
    public int leftScore;
    public int maxScore;
    public Text skorKiri; 
    public Text skorKanan; 
    public ScoreManager manager;
    public BallController ball;  
    
        // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        skorKiri.text = manager.leftScore.ToString(); 
        skorKanan.text = manager.rightScore.ToString(); 
    }
    public void AddRightScore(int increment) 
    { 
        rightScore += increment;
        ball.ResetBall();
        if (rightScore >= maxScore) 
        { 
            GameOver(); 
        } 
    } 
 
    public void AddLeftScore(int increment) 
    { 
        leftScore += increment;
        ball.ResetBall();
        if (leftScore >= maxScore) 
        { 
            GameOver(); 
        }
    } 
 
    public void GameOver() 
    { 
    SceneManager.LoadScene("Main Menu"); 
    } 
}
